# Generated by Django 3.2.16 on 2023-05-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
